# Generated by Django 2.1.7 on 2019-03-02 17:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=50)),
                ('company_intial', models.CharField(blank=True, max_length=10)),
                ('amount_of_stock', models.IntegerField()),
                ('purchase_price', models.FloatField()),
                ('stoploss', models.FloatField()),
                ('to_sell', models.CharField(default='No', max_length=3)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
